
data:
  path: data/WLASL_npy_dataset_100_split
  output_path: outputs/WLASL_npy_dataset_100_split/
  frames_per_video: 80
  num_joints: 75   # total joints before slicing
  coord_dim: 3
  hand_slices:
    left: [33, 54]     # slice(33, 54)
    right: [54, 75]    # slice(54, 75)


proc_distances:
  representation:
    mean: 4.9096828
    std: 1.4964416
    weight: 0.5

  angle:
    mean: 1.5964086
    std: 0.8329796
    weight: 0.5


embedding_encoder:
  emb_dim: 64
  lr: 0.001
  epochs: 20
  batch_size: 256
  distance_encoder: HandEmbeddingMLP
  margin: 0.2

triplet_generation:
  num_triplets: 200000
  subsampling: 0.1
  pos_k: 30
  neg_start: 50
  neg_end: 100

transformer_model:
  epochs: 50
  batch_size: 32
  lr: 3e-4
  wd: 1e-4
  heads: 8
  layers: 4
  model_dim: 256
  use_posenc: true

  
